In [27]:
import pandas as pd
import os
import json
from sklearn.metrics import accuracy_score
from io import StringIO

In [2]:
model_to_check_list = ['results_shipsnet_v02_00',
                       'results_shipsnet_v02_01',
                       'results_shipsnet_v02_02',
                       'results_shipsnet_v02_03',]

In [3]:
all_model_best_train_acc_df = pd.DataFrame(columns=['model_variant','timestamp', 'activation', 'prior', 'best_acc', 'prior_mu', 'prior_b'])
all_model_test_acc_df = pd.DataFrame(columns=['model_variant','timestamp', 'activation', 'prior', 'best_test_acc', 'prior_mu', 'prior_b'])

for model_to_check in model_to_check_list:
    train_results_dir = os.path.join('results_shipsnet_new_uniform',model_to_check)

    search_dir = os.path.join('results_shipsnet_new_uniform',model_to_check)
    #list all .json files in the directory
    all_files = [f for f in os.listdir(search_dir)]
    json_files = [f for f in os.listdir(search_dir) if f.endswith('.json')]

    # excluding the format, get the last 16 characters of each filename
    timestamps = [f[:-5][-16:] for f in json_files]
    print("Timestamps found count:", len(timestamps))

    config_files = {}
    guide_files = {}
    model_files = {}
    param_files = {}
    prediction_files = {}

    for timestamp in timestamps:
        config_files[timestamp] = [f for f in all_files if timestamp in f and f.endswith('.json')][0]
        guide_files[timestamp] = [f for f in all_files if timestamp in f and f.startswith('guide')][0]
        model_files[timestamp] = [f for f in all_files if timestamp in f and f.startswith('model')][0]
        param_files[timestamp] = [f for f in all_files if timestamp in f and f.startswith('param')][0]
        prediction_files[timestamp] = [f for f in all_files if timestamp in f and f.endswith('.csv') and f.startswith('predictions')][0]

    def load_model_config(timestamp):
        config_path = os.path.join(search_dir, config_files[timestamp])

        with open(config_path, 'r') as f:
            model_config = json.load(f)

        return model_config
    
    best_acc_df = pd.DataFrame(columns=['model_variant','timestamp', 'activation', 'prior', 'best_acc', 'prior_mu', 'prior_b', ])
    best_test_acc_df = pd.DataFrame(columns=['timestamp', 'activation', 'prior', 'best_test_acc', 'prior_mu', 'prior_b'])
    
    for ts in timestamps:
        model_config = load_model_config(ts)

        # use pandas method of concat
        best_acc_df = pd.concat([best_acc_df, pd.DataFrame({
            'model_variant': [model_to_check],
            'timestamp': [ts],
            'activation': [model_config['activation']],
            'prior': [model_config['prior']],
            'best_acc': [model_config['best_accuracy']],
            'prior_mu': [model_config['prior_params']['mu']],
            'prior_b': [model_config['prior_params']['b']]
        })], ignore_index=True)

        

        # Load the predictions
        pred_path = os.path.join('results_shipsnet_new_uniform',model_to_check, prediction_files[ts])
        predictions = pd.read_csv(pred_path)

        # Calculate the accuracy
        y_true = predictions['True Label']
        y_pred = predictions['Predicted Label']
        best_test_acc = accuracy_score(y_true, y_pred)


        # Append to the DataFrame
        best_test_acc_df = pd.concat([best_test_acc_df, pd.DataFrame({
            'model_variant': [model_to_check],
            'timestamp': [ts],
            'activation': [model_config['activation']],
            'prior': [model_config['prior']],
            'best_test_acc': [best_test_acc],
            'prior_mu': [model_config['prior_params']['mu']],
            'prior_b': [model_config['prior_params']['b']]
        })], ignore_index=True)

        
    all_model_best_train_acc_df = pd.concat([all_model_best_train_acc_df, best_acc_df], ignore_index=True)
    all_model_test_acc_df = pd.concat([all_model_test_acc_df, best_test_acc_df], ignore_index=True)

Timestamps found count: 63

C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\1699061748.py:44: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  best_acc_df = pd.concat([best_acc_df, pd.DataFrame({
C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\1699061748.py:67: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  best_test_acc_df = pd.concat([best_test_acc_df, pd.DataFrame({
C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\1699061748.py:78: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_model_best_train_acc_df = pd.concat([all_model_best_train_acc_df, best_acc_df], ignore_index=True)
C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\1699061748.py:79: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_model_test_acc_df = pd.concat([all_model_test_acc_df, best_test_acc_df], ignore_index=True)
C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\1699061748.py:44: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  best_acc_df = pd.concat([best_acc_df, pd.DataFrame({
C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\1699061748.py:67: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  best_test_acc_df = pd.concat([best_test_acc_df, pd.DataFrame({

Timestamps found count: 63
Timestamps found count: 63

C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\1699061748.py:44: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  best_acc_df = pd.concat([best_acc_df, pd.DataFrame({
C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\1699061748.py:67: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  best_test_acc_df = pd.concat([best_test_acc_df, pd.DataFrame({

Timestamps found count: 63

C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\1699061748.py:44: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  best_acc_df = pd.concat([best_acc_df, pd.DataFrame({
C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\1699061748.py:67: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  best_test_acc_df = pd.concat([best_test_acc_df, pd.DataFrame({

In [4]:
all_model_best_train_acc_df

,model_variant,timestamp,activation,prior,best_acc,prior_mu,prior_b
0,results_shipsnet_v02_00,_20250806_090014,actRWG,gaussian,0.645312,0.0,10.0
1,results_shipsnet_v02_00,_20250806_092151,actRWG,gaussian,0.690937,0.0,1.0
2,results_shipsnet_v02_00,_20250806_094253,actRWG,gaussian,0.746875,0.0,0.1
3,results_shipsnet_v02_00,_20250806_085758,actRWG,laplace,0.636250,0.0,10.0
4,results_shipsnet_v02_00,_20250806_091924,actRWG,laplace,0.667813,0.0,1.0
...,...,...,...,...,...,...,...
247,results_shipsnet_v02_03,_20250808_023435,tanh,laplace,0.765312,0.0,1.0
248,results_shipsnet_v02_03,_20250808_030304,tanh,laplace,0.614688,0.0,0.1
249,results_shipsnet_v02_03,_20250808_012843,tanh,uniform,0.819063,0.0,10.0
250,results_shipsnet_v02_03,_20250808_015333,tanh,uniform,0.810000,0.0,1.0
251,results_shipsnet_v02_03,_20250808_020556,tanh,uniform,0.922813,0.0,0.1

In [5]:
all_model_best_train_acc_df[(all_model_best_train_acc_df['prior']=='gaussian') &(all_model_best_train_acc_df['activation']=='relu') &(all_model_best_train_acc_df['model_variant']=='results_shipsnet_v02_01')]

,model_variant,timestamp,activation,prior,best_acc,prior_mu,prior_b
90,results_shipsnet_v02_01,_20250807_023923,relu,gaussian,0.717500,0.0,10.0
91,results_shipsnet_v02_01,_20250807_035320,relu,gaussian,0.866250,0.0,1.0
92,results_shipsnet_v02_01,_20250807_050924,relu,gaussian,0.750625,0.0,0.1

In [6]:
all_model_test_acc_df

,model_variant,timestamp,activation,prior,best_test_acc,prior_mu,prior_b
0,results_shipsnet_v02_00,_20250806_090014,actRWG,gaussian,0.72625,0.0,10.0
1,results_shipsnet_v02_00,_20250806_092151,actRWG,gaussian,0.75625,0.0,1.0
2,results_shipsnet_v02_00,_20250806_094253,actRWG,gaussian,0.75000,0.0,0.1
3,results_shipsnet_v02_00,_20250806_085758,actRWG,laplace,0.75625,0.0,10.0
4,results_shipsnet_v02_00,_20250806_091924,actRWG,laplace,0.75750,0.0,1.0
...,...,...,...,...,...,...,...
247,results_shipsnet_v02_03,_20250808_023435,tanh,laplace,0.88125,0.0,1.0
248,results_shipsnet_v02_03,_20250808_030304,tanh,laplace,0.71750,0.0,0.1
249,results_shipsnet_v02_03,_20250808_012843,tanh,uniform,0.91250,0.0,10.0
250,results_shipsnet_v02_03,_20250808_015333,tanh,uniform,0.90750,0.0,1.0
251,results_shipsnet_v02_03,_20250808_020556,tanh,uniform,0.90625,0.0,0.1

In [7]:
all_model_best_train_acc_df.groupby(['model_variant', 'activation', 'prior', 'prior_mu', 'prior_b']).agg({'best_acc': 'count'}).reset_index().sort_values(by='best_acc', ascending=False)

               model_variant activation     prior  prior_mu  prior_b  best_acc
0    results_shipsnet_v02_00     actRWG  gaussian       0.0      0.1         1
1    results_shipsnet_v02_00     actRWG  gaussian       0.0      1.0         1
2    results_shipsnet_v02_00     actRWG  gaussian       0.0     10.0         1
3    results_shipsnet_v02_00     actRWG   laplace       0.0      0.1         1
4    results_shipsnet_v02_00     actRWG   laplace       0.0      1.0         1
..                       ...        ...       ...       ...      ...       ...
247  results_shipsnet_v02_03       tanh   laplace       0.0      1.0         1
248  results_shipsnet_v02_03       tanh   laplace       0.0     10.0         1
249  results_shipsnet_v02_03       tanh   uniform       0.0      0.1         1
250  results_shipsnet_v02_03       tanh   uniform       0.0      1.0         1
251  results_shipsnet_v02_03       tanh   uniform       0.0     10.0         1

[252 rows x 6 columns]

In [92]:
def create_neat_latex(pivot_table):

    act_cols = ["actRWG", "actWG", "relu", "relu6", "sigmoid", "sin", "tanh"]

    df = pivot_table.copy()

    # Calculate mean for these columns
    avg_row = df[act_cols + ["average"]].astype(float).mean()

    # Build a row with the right number of columns for your table
    summary = pd.Series(
        ["", "Average", ""] + [f"{v:.4f}" for v in avg_row],
        index=df.columns
    )

    df = pd.concat([df, pd.DataFrame([summary])], ignore_index=True)

    # Wrap row max values with the macro \B{1}{value}
    def wrap_row(row):
        maxv = row[act_cols].max()
        for c in act_cols:
            v = float(row[c])
            row[c] = r"\B{%d}{%0.4f}" % (1 if v == maxv else 0, v)
        return row

    df = df.apply(wrap_row, axis=1)


    # Format average
    if "average" in df.columns:
        df["average"] = df["average"].map(lambda x: f"{float(x):.4f}")

    # Generate LaTeX without escaping macros
    latex_lines = df.to_latex(index=False, escape=False).splitlines()

    # Add macro definition
    #macro = r"\newcommand{\B}[2]{\ifnum#1=1 \textbf{#2}\else #2\fi}"
    macro = r"\begin{table}[h]"
    final_lines = [macro]

    # Insert \midrule after every model_variant change
    header_done = False
    last_model = None
    for idx, line in enumerate(latex_lines):
        if not header_done:
            final_lines.append(line)
            if line.strip().endswith(r"\midrule"):
                header_done = True
            continue

        # Extract model name from start of line (split by &)
        model_name = line.strip().split("&")[0].strip()
        last_model = latex_lines[idx-1].strip().split("&")[0].strip() if idx > 0 else None
        
        #print("Model name:", model_name, "Last model:", last_model)
        if last_model is not None and model_name != last_model and not line.startswith(r"\bottomrule") and line.startswith(r"Model") and not last_model.startswith(r"\midrule"):
            final_lines.append(r"\midrule")
        if last_model == "Model 3" and model_name == "":
            final_lines.append(r"\midrule")
        final_lines.append(line)
        #last_model = model_name

    final_lines.append(r"\caption{...}")
    final_lines.append(r"\label{table:...}")
    final_lines.append(r"\end{table}")
    #print(final_lines)
    # Join into final LaTeX string
    latex_text = "\n".join(final_lines)
    latex_text = latex_text.replace('llrllllllll', 'llrrrrrrrrr')
    latex_text = latex_text.replace('10.000000', '10')
    latex_text = latex_text.replace('1.000000', '1')
    latex_text = latex_text.replace('0.100000', '0.1')
    latex_text = latex_text.replace('model_variant', 'model\\_variant')
    latex_text = latex_text.replace('prior_b', 'prior\\_b')
    return (latex_text)

In [8]:
all_model_best_acc_df_pivot = all_model_best_train_acc_df[all_model_best_train_acc_df['prior_b']==0.10000000149011612]
all_model_best_acc_df_pivot = all_model_best_acc_df_pivot.pivot_table(index=['model_variant', 'prior', 'prior_b'], columns='activation', values='best_acc')
all_model_best_acc_df_pivot = all_model_best_acc_df_pivot.reset_index()
all_model_best_acc_df_pivot['model_variant'] = all_model_best_acc_df_pivot['model_variant'].map({
    'results_shipsnet_v02_00': 'Model 0',
    'results_shipsnet_v02_01': 'Model 1',
    'results_shipsnet_v02_02': 'Model 2',
    'results_shipsnet_v02_03': 'Model 3'
})
all_model_best_acc_df_pivot

activation,model_variant,prior,prior_b,actRWG,actWG,relu,relu6,sigmoid,sin,tanh
0,Model 0,gaussian,0.1,0.746875,0.710000,0.750313,0.750313,0.743437,0.717187,0.715000
1,Model 0,laplace,0.1,0.655937,0.605625,0.717187,0.721250,0.717812,0.626563,0.614062
2,Model 0,uniform,0.1,0.921562,0.935000,0.930625,0.930000,0.862500,0.931562,0.913125
3,Model 1,gaussian,0.1,0.746875,0.710000,0.750625,0.750625,0.743437,0.717187,0.714375
4,Model 1,laplace,0.1,0.656250,0.604375,0.716875,0.724063,0.718437,0.623437,0.613750
5,Model 1,uniform,0.1,0.934375,0.929688,0.929063,0.927500,0.862500,0.931250,0.913125
6,Model 2,gaussian,0.1,0.743437,0.687187,0.744062,0.743750,0.735938,0.687500,0.688750
7,Model 2,laplace,0.1,0.669687,0.612812,0.719375,0.722500,0.716875,0.645312,0.619687
8,Model 2,uniform,0.1,0.931875,0.943438,0.918125,0.929688,0.858125,0.928125,0.927500
9,Model 3,gaussian,0.1,0.746875,0.710625,0.750313,0.750625,0.743437,0.717187,0.714375
10,Model 3,laplace,0.1,0.656875,0.603437,0.715625,0.721562,0.718750,0.621250,0.614688
11,Model 3,uniform,0.1,0.925625,0.933125,0.930000,0.927813,0.862500,0.931875,0.922813

In [9]:
latex_text = all_model_best_acc_df_pivot.to_latex(index=False,
                  formatters={"name": str.upper},
                  float_format="{:.4f}".format)
latex_text = latex_text.replace('0.1000', '0.1')
latex_text = latex_text.replace('model_variant', 'model\_variant')
latex_text = latex_text.replace('prior_b', 'prior\_b')
print(latex_text)

<>:5: SyntaxWarning: invalid escape sequence '\_'
<>:6: SyntaxWarning: invalid escape sequence '\_'
<>:5: SyntaxWarning: invalid escape sequence '\_'
<>:6: SyntaxWarning: invalid escape sequence '\_'
C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\1039078576.py:5: SyntaxWarning: invalid escape sequence '\_'
  latex_text = latex_text.replace('model_variant', 'model\_variant')
C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\1039078576.py:6: SyntaxWarning: invalid escape sequence '\_'
  latex_text = latex_text.replace('prior_b', 'prior\_b')

\begin{tabular}{llrrrrrrrr}
\toprule
model\_variant & prior & prior\_b & actRWG & actWG & relu & relu6 & sigmoid & sin & tanh \\
\midrule
Model 0 & gaussian & 0.1 & 0.7469 & 0.7100 & 0.7503 & 0.7503 & 0.7434 & 0.7172 & 0.7150 \\
Model 0 & laplace & 0.1 & 0.6559 & 0.6056 & 0.7172 & 0.7212 & 0.7178 & 0.6266 & 0.6141 \\
Model 0 & uniform & 0.1 & 0.9216 & 0.9350 & 0.9306 & 0.9300 & 0.8625 & 0.9316 & 0.9131 \\
Model 1 & gaussian & 0.1 & 0.7469 & 0.7100 & 0.7506 & 0.7506 & 0.7434 & 0.7172 & 0.7144 \\
Model 1 & laplace & 0.1 & 0.6562 & 0.6044 & 0.7169 & 0.7241 & 0.7184 & 0.6234 & 0.6138 \\
Model 1 & uniform & 0.1 & 0.9344 & 0.9297 & 0.9291 & 0.9275 & 0.8625 & 0.9313 & 0.9131 \\
Model 2 & gaussian & 0.1 & 0.7434 & 0.6872 & 0.7441 & 0.7438 & 0.7359 & 0.6875 & 0.6887 \\
Model 2 & laplace & 0.1 & 0.6697 & 0.6128 & 0.7194 & 0.7225 & 0.7169 & 0.6453 & 0.6197 \\
Model 2 & uniform & 0.1 & 0.9319 & 0.9434 & 0.9181 & 0.9297 & 0.8581 & 0.9281 & 0.9275 \\
Model 3 & gaussian & 0.1 & 0.7469 & 0.7106 & 0.7503 & 0.7506 & 0.7434 & 0.7172 & 0.7144 \\
Model 3 & laplace & 0.1 & 0.6569 & 0.6034 & 0.7156 & 0.7216 & 0.7188 & 0.6212 & 0.6147 \\
Model 3 & uniform & 0.1 & 0.9256 & 0.9331 & 0.9300 & 0.9278 & 0.8625 & 0.9319 & 0.9228 \\
\bottomrule
\end{tabular}

In [10]:
#pivot the dataframe, the columns represents the activation function, the index is the [model_variant, activation, prior, prior_b]
all_model_best_acc_df_pivot = all_model_best_acc_df_pivot = all_model_best_train_acc_df[all_model_best_train_acc_df['prior_b']==1]
all_model_best_acc_df_pivot = all_model_best_acc_df_pivot.pivot_table(index=['model_variant', 'prior', 'prior_b'], columns='activation', values='best_acc')
all_model_best_acc_df_pivot = all_model_best_acc_df_pivot.reset_index()
# rename the model variant with a mapping that I give
all_model_best_acc_df_pivot['model_variant'] = all_model_best_acc_df_pivot['model_variant'].map({
    'results_shipsnet_v02_00': 'Model 0',
    'results_shipsnet_v02_01': 'Model 1',
    'results_shipsnet_v02_02': 'Model 2',
    'results_shipsnet_v02_03': 'Model 3'
})

all_model_best_acc_df_pivot

activation,model_variant,prior,prior_b,actRWG,actWG,relu,relu6,sigmoid,sin,tanh
0,Model 0,gaussian,1.0,0.690937,0.767813,0.871563,0.825000,0.699375,0.823125,0.789375
1,Model 0,laplace,1.0,0.667813,0.699063,0.870313,0.783125,0.697500,0.774062,0.770625
2,Model 0,uniform,1.0,0.745938,0.777813,0.868437,0.836250,0.797500,0.869375,0.811562
3,Model 1,gaussian,1.0,0.698438,0.768437,0.866250,0.812500,0.696562,0.819063,0.777188
4,Model 1,laplace,1.0,0.678125,0.695312,0.846875,0.786250,0.696250,0.775000,0.765625
5,Model 1,uniform,1.0,0.743437,0.780000,0.874375,0.815312,0.794687,0.875625,0.819375
6,Model 2,gaussian,1.0,0.720625,0.780312,0.888437,0.863125,0.694375,0.855938,0.830625
7,Model 2,laplace,1.0,0.701250,0.731250,0.878750,0.850000,0.686562,0.795937,0.797813
8,Model 2,uniform,1.0,0.736563,0.781563,0.886250,0.869375,0.802500,0.890312,0.807187
9,Model 3,gaussian,1.0,0.694688,0.776875,0.871875,0.823750,0.695000,0.818438,0.777188
10,Model 3,laplace,1.0,0.680937,0.700625,0.854062,0.781563,0.692187,0.770938,0.765312
11,Model 3,uniform,1.0,0.673750,0.768750,0.874687,0.812813,0.791875,0.875938,0.810000

In [11]:
latex_text = all_model_best_acc_df_pivot.to_latex(index=False,
                  formatters={"name": str.upper},
                  float_format="{:.4f}".format)
latex_text = latex_text.replace('1.0000', '1')
latex_text = latex_text.replace('model_variant', 'model\_variant')
latex_text = latex_text.replace('prior_b', 'prior\_b')
print(latex_text)

\begin{tabular}{llrrrrrrrr}
\toprule
model\_variant & prior & prior\_b & actRWG & actWG & relu & relu6 & sigmoid & sin & tanh \\
\midrule
Model 0 & gaussian & 1 & 0.6909 & 0.7678 & 0.8716 & 0.8250 & 0.6994 & 0.8231 & 0.7894 \\
Model 0 & laplace & 1 & 0.6678 & 0.6991 & 0.8703 & 0.7831 & 0.6975 & 0.7741 & 0.7706 \\
Model 0 & uniform & 1 & 0.7459 & 0.7778 & 0.8684 & 0.8363 & 0.7975 & 0.8694 & 0.8116 \\
Model 1 & gaussian & 1 & 0.6984 & 0.7684 & 0.8662 & 0.8125 & 0.6966 & 0.8191 & 0.7772 \\
Model 1 & laplace & 1 & 0.6781 & 0.6953 & 0.8469 & 0.7863 & 0.6963 & 0.7750 & 0.7656 \\
Model 1 & uniform & 1 & 0.7434 & 0.7800 & 0.8744 & 0.8153 & 0.7947 & 0.8756 & 0.8194 \\
Model 2 & gaussian & 1 & 0.7206 & 0.7803 & 0.8884 & 0.8631 & 0.6944 & 0.8559 & 0.8306 \\
Model 2 & laplace & 1 & 0.7013 & 0.7312 & 0.8788 & 0.8500 & 0.6866 & 0.7959 & 0.7978 \\
Model 2 & uniform & 1 & 0.7366 & 0.7816 & 0.8862 & 0.8694 & 0.8025 & 0.8903 & 0.8072 \\
Model 3 & gaussian & 1 & 0.6947 & 0.7769 & 0.8719 & 0.8237 & 0.6950 & 0.8184 & 0.7772 \\
Model 3 & laplace & 1 & 0.6809 & 0.7006 & 0.8541 & 0.7816 & 0.6922 & 0.7709 & 0.7653 \\
Model 3 & uniform & 1 & 0.6737 & 0.7688 & 0.8747 & 0.8128 & 0.7919 & 0.8759 & 0.8100 \\
\bottomrule
\end{tabular}

<>:5: SyntaxWarning: invalid escape sequence '\_'
<>:6: SyntaxWarning: invalid escape sequence '\_'
<>:5: SyntaxWarning: invalid escape sequence '\_'
<>:6: SyntaxWarning: invalid escape sequence '\_'
C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\4068192951.py:5: SyntaxWarning: invalid escape sequence '\_'
  latex_text = latex_text.replace('model_variant', 'model\_variant')
C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\4068192951.py:6: SyntaxWarning: invalid escape sequence '\_'
  latex_text = latex_text.replace('prior_b', 'prior\_b')

In [12]:
all_model_best_acc_df_pivot = all_model_best_train_acc_df[all_model_best_train_acc_df['prior_b']==10]
all_model_best_acc_df_pivot = all_model_best_acc_df_pivot.pivot_table(index=['model_variant', 'prior', 'prior_b'], columns='activation', values='best_acc')
all_model_best_acc_df_pivot = all_model_best_acc_df_pivot.reset_index()
all_model_best_acc_df_pivot['model_variant'] = all_model_best_acc_df_pivot['model_variant'].map({
    'results_shipsnet_v02_00': 'Model 0',
    'results_shipsnet_v02_01': 'Model 1',
    'results_shipsnet_v02_02': 'Model 2',
    'results_shipsnet_v02_03': 'Model 3'
})

all_model_best_acc_df_pivot

activation,model_variant,prior,prior_b,actRWG,actWG,relu,relu6,sigmoid,sin,tanh
0,Model 0,gaussian,10.0,0.645312,0.648750,0.832812,0.682187,0.694375,0.669063,0.779687
1,Model 0,laplace,10.0,0.636250,0.648438,0.822812,0.682187,0.674375,0.664687,0.767188
2,Model 0,uniform,10.0,0.678438,0.696875,0.866563,0.670625,0.816875,0.696562,0.817813
3,Model 1,gaussian,10.0,0.651250,0.653750,0.717500,0.702500,0.700000,0.674375,0.780625
4,Model 1,laplace,10.0,0.648125,0.649375,0.705625,0.692187,0.673125,0.666875,0.765938
5,Model 1,uniform,10.0,0.680312,0.707812,0.825937,0.674063,0.822187,0.703438,0.820000
6,Model 2,gaussian,10.0,0.687187,0.691875,0.833125,0.735625,0.722812,0.696875,0.812187
7,Model 2,laplace,10.0,0.675000,0.670000,0.813438,0.715625,0.709375,0.663438,0.801562
8,Model 2,uniform,10.0,0.709375,0.721250,0.886875,0.779375,0.854062,0.687813,0.842500
9,Model 3,gaussian,10.0,0.657500,0.655625,0.834688,0.695937,0.700625,0.684688,0.780937
10,Model 3,laplace,10.0,0.635312,0.658125,0.818750,0.684688,0.671875,0.684688,0.768125
11,Model 3,uniform,10.0,0.672813,0.695625,0.865625,0.683125,0.828438,0.695625,0.819063

In [13]:
latex_text = all_model_best_acc_df_pivot.to_latex(index=False,
                  formatters={"name": str.upper},
                  float_format="{:.4f}".format)
latex_text = latex_text.replace('10.0000', '10')
latex_text = latex_text.replace('model_variant', 'model\_variant')
latex_text = latex_text.replace('prior_b', 'prior\_b')
print(latex_text)

\begin{tabular}{llrrrrrrrr}
\toprule
model\_variant & prior & prior\_b & actRWG & actWG & relu & relu6 & sigmoid & sin & tanh \\
\midrule
Model 0 & gaussian & 10 & 0.6453 & 0.6488 & 0.8328 & 0.6822 & 0.6944 & 0.6691 & 0.7797 \\
Model 0 & laplace & 10 & 0.6362 & 0.6484 & 0.8228 & 0.6822 & 0.6744 & 0.6647 & 0.7672 \\
Model 0 & uniform & 10 & 0.6784 & 0.6969 & 0.8666 & 0.6706 & 0.8169 & 0.6966 & 0.8178 \\
Model 1 & gaussian & 10 & 0.6512 & 0.6538 & 0.7175 & 0.7025 & 0.7000 & 0.6744 & 0.7806 \\
Model 1 & laplace & 10 & 0.6481 & 0.6494 & 0.7056 & 0.6922 & 0.6731 & 0.6669 & 0.7659 \\
Model 1 & uniform & 10 & 0.6803 & 0.7078 & 0.8259 & 0.6741 & 0.8222 & 0.7034 & 0.8200 \\
Model 2 & gaussian & 10 & 0.6872 & 0.6919 & 0.8331 & 0.7356 & 0.7228 & 0.6969 & 0.8122 \\
Model 2 & laplace & 10 & 0.6750 & 0.6700 & 0.8134 & 0.7156 & 0.7094 & 0.6634 & 0.8016 \\
Model 2 & uniform & 10 & 0.7094 & 0.7212 & 0.8869 & 0.7794 & 0.8541 & 0.6878 & 0.8425 \\
Model 3 & gaussian & 10 & 0.6575 & 0.6556 & 0.8347 & 0.6959 & 0.7006 & 0.6847 & 0.7809 \\
Model 3 & laplace & 10 & 0.6353 & 0.6581 & 0.8187 & 0.6847 & 0.6719 & 0.6847 & 0.7681 \\
Model 3 & uniform & 10 & 0.6728 & 0.6956 & 0.8656 & 0.6831 & 0.8284 & 0.6956 & 0.8191 \\
\bottomrule
\end{tabular}

<>:5: SyntaxWarning: invalid escape sequence '\_'
<>:6: SyntaxWarning: invalid escape sequence '\_'
<>:5: SyntaxWarning: invalid escape sequence '\_'
<>:6: SyntaxWarning: invalid escape sequence '\_'
C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\258232727.py:5: SyntaxWarning: invalid escape sequence '\_'
  latex_text = latex_text.replace('model_variant', 'model\_variant')
C:\Users\Revalda Putawara\AppData\Local\Temp\ipykernel_2900\258232727.py:6: SyntaxWarning: invalid escape sequence '\_'
  latex_text = latex_text.replace('prior_b', 'prior\_b')

In [14]:
all_model_test_acc_df

,model_variant,timestamp,activation,prior,best_test_acc,prior_mu,prior_b
0,results_shipsnet_v02_00,_20250806_090014,actRWG,gaussian,0.72625,0.0,10.0
1,results_shipsnet_v02_00,_20250806_092151,actRWG,gaussian,0.75625,0.0,1.0
2,results_shipsnet_v02_00,_20250806_094253,actRWG,gaussian,0.75000,0.0,0.1
3,results_shipsnet_v02_00,_20250806_085758,actRWG,laplace,0.75625,0.0,10.0
4,results_shipsnet_v02_00,_20250806_091924,actRWG,laplace,0.75750,0.0,1.0
...,...,...,...,...,...,...,...
247,results_shipsnet_v02_03,_20250808_023435,tanh,laplace,0.88125,0.0,1.0
248,results_shipsnet_v02_03,_20250808_030304,tanh,laplace,0.71750,0.0,0.1
249,results_shipsnet_v02_03,_20250808_012843,tanh,uniform,0.91250,0.0,10.0
250,results_shipsnet_v02_03,_20250808_015333,tanh,uniform,0.90750,0.0,1.0
251,results_shipsnet_v02_03,_20250808_020556,tanh,uniform,0.90625,0.0,0.1

In [118]:
all_model_test_acc_df_pivot = all_model_test_acc_df[all_model_test_acc_df['prior_b']==0.10000000149011612]
all_model_test_acc_df_pivot = all_model_test_acc_df_pivot.pivot_table(index=['model_variant', 'prior', 'prior_b'], columns='activation', values='best_test_acc')
all_model_test_acc_df_pivot = all_model_test_acc_df_pivot.reset_index()
all_model_test_acc_df_pivot['model_variant'] = all_model_test_acc_df_pivot['model_variant'].map({
    'results_shipsnet_v02_00': 'Model 0',
    'results_shipsnet_v02_01': 'Model 1',
    'results_shipsnet_v02_02': 'Model 2',
    'results_shipsnet_v02_03': 'Model 3'
})

# average on the columns of activation
all_model_test_acc_df_pivot_mean = all_model_test_acc_df_pivot[all_model_test_acc_df['activation'].unique().tolist()].mean(axis=1).round(4)
# add the mean as a new column to the pivot table
all_model_test_acc_df_pivot['average'] = all_model_test_acc_df_pivot_mean


latex_text = create_neat_latex(all_model_test_acc_df_pivot)
print(latex_text)

all_model_test_acc_df_filtered = all_model_test_acc_df[all_model_test_acc_df['prior_b']==0.10000000149011612]

print(all_model_test_acc_df_filtered[['prior','best_test_acc']].groupby(['prior']).mean().reset_index().round(4))

print(all_model_test_acc_df_filtered[['model_variant','best_test_acc']].groupby(['model_variant']).mean().reset_index().round(4))

\begin{table}[h]
\begin{tabular}{lllllllllll}
\toprule
model\_variant & prior & prior\_b & actRWG & actWG & relu & relu6 & sigmoid & sin & tanh & average \\
\midrule
Model 0 & gaussian & 0.1 & \B{0}{0.7500} & \B{0}{0.7225} & \B{0}{0.7837} & \B{1}{0.7850} & \B{0}{0.7500} & \B{0}{0.7588} & \B{0}{0.7475} & 0.7568 \\
Model 0 & laplace & 0.1 & \B{0}{0.7500} & \B{0}{0.7075} & \B{1}{0.7700} & \B{0}{0.7688} & \B{0}{0.7500} & \B{0}{0.7438} & \B{0}{0.7150} & 0.7436 \\
Model 0 & uniform & 0.1 & \B{0}{0.9187} & \B{0}{0.9363} & \B{0}{0.9213} & \B{0}{0.9250} & \B{0}{0.8413} & \B{1}{0.9387} & \B{0}{0.8988} & 0.9114 \\
\midrule
Model 1 & gaussian & 0.1 & \B{0}{0.7500} & \B{0}{0.7225} & \B{1}{0.7850} & \B{1}{0.7850} & \B{0}{0.7500} & \B{0}{0.7588} & \B{0}{0.7475} & 0.7570 \\
Model 1 & laplace & 0.1 & \B{0}{0.7500} & \B{0}{0.7087} & \B{1}{0.7700} & \B{1}{0.7700} & \B{0}{0.7500} & \B{0}{0.7475} & \B{0}{0.7150} & 0.7445 \\
Model 1 & uniform & 0.1 & \B{0}{0.9100} & \B{0}{0.9313} & \B{0}{0.9237} & \B{0}{0.9187} & \B{0}{0.8387} & \B{1}{0.9387} & \B{0}{0.8988} & 0.9086 \\
\midrule
Model 2 & gaussian & 0.1 & \B{0}{0.7500} & \B{0}{0.7412} & \B{1}{0.7825} & \B{0}{0.7788} & \B{0}{0.7500} & \B{0}{0.7638} & \B{0}{0.7512} & 0.7596 \\
Model 2 & laplace & 0.1 & \B{0}{0.7462} & \B{0}{0.7175} & \B{1}{0.7987} & \B{0}{0.7950} & \B{0}{0.7400} & \B{0}{0.7512} & \B{0}{0.7312} & 0.7543 \\
Model 2 & uniform & 0.1 & \B{0}{0.9213} & \B{1}{0.9500} & \B{0}{0.9113} & \B{0}{0.9113} & \B{0}{0.8363} & \B{0}{0.7975} & \B{0}{0.9137} & 0.8916 \\
\midrule
Model 3 & gaussian & 0.1 & \B{0}{0.7500} & \B{0}{0.7225} & \B{0}{0.7850} & \B{1}{0.7863} & \B{0}{0.7500} & \B{0}{0.7588} & \B{0}{0.7488} & 0.7573 \\
Model 3 & laplace & 0.1 & \B{0}{0.7500} & \B{0}{0.7050} & \B{1}{0.7700} & \B{0}{0.7688} & \B{0}{0.7500} & \B{0}{0.7425} & \B{0}{0.7175} & 0.7434 \\
Model 3 & uniform & 0.1 & \B{0}{0.9237} & \B{0}{0.8662} & \B{0}{0.9225} & \B{0}{0.9062} & \B{0}{0.8387} & \B{1}{0.9413} & \B{0}{0.9062} & 0.9007 \\
\midrule
 & Average &  & \B{0}{0.8058} & \B{0}{0.7859} & \B{0}{0.8270} & \B{0}{0.8249} & \B{0}{0.7787} & \B{0}{0.8034} & \B{0}{0.7909} & 0.8024 \\
\bottomrule
\end{tabular}
\caption{...}
\label{table:...}
\end{table}
      prior  best_test_acc
0  gaussian         0.7577
1   laplace         0.7464
2   uniform         0.9031
             model_variant  best_test_acc
0  results_shipsnet_v02_00         0.8039
1  results_shipsnet_v02_01         0.8033
2  results_shipsnet_v02_02         0.8018
3  results_shipsnet_v02_03         0.8005

In [122]:
all_model_test_acc_df_pivot = all_model_test_acc_df[all_model_test_acc_df['prior_b']==1]
all_model_test_acc_df_pivot = all_model_test_acc_df_pivot.pivot_table(index=['model_variant', 'prior', 'prior_b'], columns='activation', values='best_test_acc')
all_model_test_acc_df_pivot = all_model_test_acc_df_pivot.reset_index()
all_model_test_acc_df_pivot['model_variant'] = all_model_test_acc_df_pivot['model_variant'].map({
    'results_shipsnet_v02_00': 'Model 0',
    'results_shipsnet_v02_01': 'Model 1',
    'results_shipsnet_v02_02': 'Model 2',
    'results_shipsnet_v02_03': 'Model 3'
})

# average on the columns of activation
all_model_test_acc_df_pivot_mean = all_model_test_acc_df_pivot[all_model_test_acc_df['activation'].unique().tolist()].mean(axis=1).round(4)
# add the mean as a new column to the pivot table
all_model_test_acc_df_pivot['average'] = all_model_test_acc_df_pivot_mean

latex_text = create_neat_latex(all_model_test_acc_df_pivot)
print(latex_text)

all_model_test_acc_df_filtered = all_model_test_acc_df[all_model_test_acc_df['prior_b']==1]

print(all_model_test_acc_df_filtered[['prior','best_test_acc']].groupby(['prior']).mean().reset_index().round(4))

print(all_model_test_acc_df_filtered[['model_variant','best_test_acc']].groupby(['model_variant']).mean().reset_index().round(4))

\begin{table}[h]
\begin{tabular}{lllllllllll}
\toprule
model\_variant & prior & prior\_b & actRWG & actWG & relu & relu6 & sigmoid & sin & tanh & average \\
\midrule
Model 0 & gaussian & 1 & \B{0}{0.7562} & \B{0}{0.7650} & \B{1}{0.9137} & \B{0}{0.8825} & \B{0}{0.8025} & \B{0}{0.7612} & \B{0}{0.8938} & 0.8250 \\
Model 0 & laplace & 1 & \B{0}{0.7575} & \B{0}{0.7538} & \B{1}{0.8975} & \B{0}{0.8562} & \B{0}{0.7675} & \B{0}{0.7500} & \B{0}{0.8750} & 0.8082 \\
Model 0 & uniform & 1 & \B{0}{0.8063} & \B{0}{0.8263} & \B{1}{0.9025} & \B{0}{0.8712} & \B{0}{0.8237} & \B{0}{0.8762} & \B{0}{0.8662} & 0.8532 \\
\midrule
Model 1 & gaussian & 1 & \B{0}{0.7600} & \B{0}{0.7612} & \B{1}{0.9137} & \B{0}{0.8788} & \B{0}{0.8050} & \B{0}{0.7512} & \B{0}{0.8925} & 0.8232 \\
Model 1 & laplace & 1 & \B{0}{0.7475} & \B{0}{0.7550} & \B{1}{0.9113} & \B{0}{0.8700} & \B{0}{0.7650} & \B{0}{0.7500} & \B{0}{0.8762} & 0.8107 \\
Model 1 & uniform & 1 & \B{0}{0.8325} & \B{0}{0.8125} & \B{0}{0.9125} & \B{0}{0.8762} & \B{0}{0.8237} & \B{1}{0.9150} & \B{0}{0.8875} & 0.8657 \\
\midrule
Model 2 & gaussian & 1 & \B{0}{0.7525} & \B{0}{0.7588} & \B{1}{0.9100} & \B{0}{0.8925} & \B{0}{0.7525} & \B{0}{0.7825} & \B{0}{0.8862} & 0.8193 \\
Model 2 & laplace & 1 & \B{0}{0.7488} & \B{0}{0.7588} & \B{1}{0.9100} & \B{0}{0.8825} & \B{0}{0.7488} & \B{0}{0.7512} & \B{0}{0.8738} & 0.8105 \\
Model 2 & uniform & 1 & \B{0}{0.7400} & \B{0}{0.8213} & \B{0}{0.9150} & \B{0}{0.8875} & \B{0}{0.8225} & \B{1}{0.9175} & \B{0}{0.8662} & 0.8529 \\
\midrule
Model 3 & gaussian & 1 & \B{0}{0.7538} & \B{0}{0.7612} & \B{1}{0.9200} & \B{0}{0.8825} & \B{0}{0.7963} & \B{0}{0.7625} & \B{0}{0.8925} & 0.8241 \\
Model 3 & laplace & 1 & \B{0}{0.7500} & \B{0}{0.7488} & \B{1}{0.9175} & \B{0}{0.8738} & \B{0}{0.7625} & \B{0}{0.7512} & \B{0}{0.8812} & 0.8121 \\
Model 3 & uniform & 1 & \B{0}{0.7362} & \B{0}{0.8225} & \B{1}{0.9237} & \B{0}{0.7512} & \B{0}{0.8000} & \B{0}{0.9163} & \B{0}{0.9075} & 0.8368 \\
\midrule
 & Average &  & \B{0}{0.7618} & \B{0}{0.7787} & \B{0}{0.9123} & \B{0}{0.8671} & \B{0}{0.7892} & \B{0}{0.8071} & \B{0}{0.8832} & 0.8285 \\
\bottomrule
\end{tabular}
\caption{...}
\label{table:...}
\end{table}
      prior  best_test_acc
0  gaussian         0.8229
1   laplace         0.8104
2   uniform         0.8521
             model_variant  best_test_acc
0  results_shipsnet_v02_00         0.8288
1  results_shipsnet_v02_01         0.8332
2  results_shipsnet_v02_02         0.8276
3  results_shipsnet_v02_03         0.8243

In [120]:
all_model_test_acc_df_pivot = all_model_test_acc_df[all_model_test_acc_df['prior_b']==10]
all_model_test_acc_df_pivot = all_model_test_acc_df_pivot.pivot_table(index=['model_variant', 'prior', 'prior_b'], columns='activation', values='best_test_acc')
all_model_test_acc_df_pivot = all_model_test_acc_df_pivot.reset_index()
all_model_test_acc_df_pivot['model_variant'] = all_model_test_acc_df_pivot['model_variant'].map({
    'results_shipsnet_v02_00': 'Model 0',
    'results_shipsnet_v02_01': 'Model 1',
    'results_shipsnet_v02_02': 'Model 2',
    'results_shipsnet_v02_03': 'Model 3'
})

# average on the columns of activation
all_model_test_acc_df_pivot_mean = all_model_test_acc_df_pivot[all_model_test_acc_df['activation'].unique().tolist()].mean(axis=1).round(4)
# add the mean as a new column to the pivot table
all_model_test_acc_df_pivot['average'] = all_model_test_acc_df_pivot_mean

latex_text = create_neat_latex(all_model_test_acc_df_pivot)
print(latex_text)

all_model_test_acc_df_filtered = all_model_test_acc_df[all_model_test_acc_df['prior_b']==10]

print(all_model_test_acc_df_filtered[['prior','best_test_acc']].groupby(['prior']).mean().reset_index().round(4))

print(all_model_test_acc_df_filtered[['model_variant','best_test_acc']].groupby(['model_variant']).mean().reset_index().round(4))

\begin{table}[h]
\begin{tabular}{lllllllllll}
\toprule
model\_variant & prior & prior\_b & actRWG & actWG & relu & relu6 & sigmoid & sin & tanh & average \\
\midrule
Model 0 & gaussian & 10 & \B{0}{0.7262} & \B{0}{0.7300} & \B{0}{0.8550} & \B{0}{0.8237} & \B{0}{0.8100} & \B{0}{0.7425} & \B{1}{0.8738} & 0.7945 \\
Model 0 & laplace & 10 & \B{0}{0.7562} & \B{0}{0.7550} & \B{0}{0.8612} & \B{0}{0.8113} & \B{0}{0.7712} & \B{0}{0.7488} & \B{1}{0.8700} & 0.7962 \\
Model 0 & uniform & 10 & \B{0}{0.7612} & \B{0}{0.7975} & \B{1}{0.9075} & \B{0}{0.7600} & \B{0}{0.8962} & \B{0}{0.7500} & \B{0}{0.9062} & 0.8255 \\
\midrule
Model 1 & gaussian & 10 & \B{0}{0.7538} & \B{0}{0.7488} & \B{0}{0.7913} & \B{0}{0.8137} & \B{0}{0.8275} & \B{0}{0.7475} & \B{1}{0.8738} & 0.7938 \\
Model 1 & laplace & 10 & \B{0}{0.7488} & \B{0}{0.7462} & \B{0}{0.7850} & \B{0}{0.7950} & \B{0}{0.7662} & \B{0}{0.7500} & \B{1}{0.8688} & 0.7800 \\
Model 1 & uniform & 10 & \B{0}{0.7488} & \B{0}{0.8287} & \B{0}{0.9075} & \B{0}{0.8137} & \B{0}{0.8912} & \B{0}{0.7500} & \B{1}{0.9150} & 0.8364 \\
\midrule
Model 2 & gaussian & 10 & \B{0}{0.7488} & \B{0}{0.7500} & \B{0}{0.8562} & \B{0}{0.8087} & \B{0}{0.7675} & \B{0}{0.7500} & \B{1}{0.8850} & 0.7952 \\
Model 2 & laplace & 10 & \B{0}{0.7488} & \B{0}{0.7512} & \B{0}{0.8488} & \B{0}{0.7825} & \B{0}{0.7550} & \B{0}{0.7488} & \B{1}{0.8600} & 0.7850 \\
Model 2 & uniform & 10 & \B{0}{0.7775} & \B{0}{0.7900} & \B{0}{0.8988} & \B{0}{0.8688} & \B{0}{0.8912} & \B{0}{0.7500} & \B{1}{0.9062} & 0.8404 \\
\midrule
Model 3 & gaussian & 10 & \B{0}{0.7525} & \B{0}{0.7500} & \B{0}{0.8575} & \B{0}{0.8213} & \B{0}{0.8187} & \B{0}{0.7488} & \B{1}{0.8812} & 0.8043 \\
Model 3 & laplace & 10 & \B{0}{0.7500} & \B{0}{0.7562} & \B{0}{0.8612} & \B{0}{0.8050} & \B{0}{0.7700} & \B{0}{0.7500} & \B{1}{0.8688} & 0.7945 \\
Model 3 & uniform & 10 & \B{0}{0.7750} & \B{0}{0.8050} & \B{0}{0.9113} & \B{0}{0.8037} & \B{0}{0.8962} & \B{0}{0.7500} & \B{1}{0.9125} & 0.8362 \\
\midrule
 & Average &  & \B{0}{0.7540} & \B{0}{0.7674} & \B{0}{0.8618} & \B{0}{0.8090} & \B{0}{0.8218} & \B{0}{0.7489} & \B{0}{0.8851} & 0.8068 \\
\bottomrule
\end{tabular}
\caption{...}
\label{table:...}
\end{table}
      prior  best_test_acc
0  gaussian         0.7969
1   laplace         0.7889
2   uniform         0.8346
             model_variant  best_test_acc
0  results_shipsnet_v02_00         0.8054
1  results_shipsnet_v02_01         0.8034
2  results_shipsnet_v02_02         0.8068
3  results_shipsnet_v02_03         0.8117

In [ ]:
search_dir = os.path.join('results_shipsnet_new_uniform',model_to_check)
#list all .json files in the directory
all_files = [f for f in os.listdir(search_dir)]
json_files = [f for f in os.listdir(search_dir) if f.endswith('.json')]

# excluding the format, get the last 16 characters of each filename
timestamps = [f[:-5][-16:] for f in json_files]
print("Timestamps found count:", len(timestamps))

# remove some timestamps that are not needed
# those are the ones that are not in the shipsnet_seu_result directory, without the .csv extension
#excluded_timestamps = [f[:-4][-16:] for f in [f for f in os.listdir('shipsnet_newslate_seu_result') if f.endswith('.csv')]]

#timestamps = [ts for ts in timestamps if ts not in excluded_timestamps]
#timestamps = timestamps[:1]
#print("After excluding, timestamps count:", len(timestamps))

In [ ]:
config_files = {}
guide_files = {}
model_files = {}
param_files = {}

for timestamp in timestamps:
    config_files[timestamp] = [f for f in all_files if timestamp in f and f.endswith('.json')][0]
    guide_files[timestamp] = [f for f in all_files if timestamp in f and f.startswith('guide')][0]
    model_files[timestamp] = [f for f in all_files if timestamp in f and f.startswith('model')][0]
    param_files[timestamp] = [f for f in all_files if timestamp in f and f.startswith('param')][0]

In [ ]:
ts_idx = 0

In [ ]:
import json

def load_model_config(timestamp):
    config_path = os.path.join(search_dir, config_files[timestamp])

    with open(config_path, 'r') as f:
        model_config = json.load(f)

    return model_config

In [ ]:
model_config = load_model_config(timestamps[ts_idx])

In [ ]:
model_config

## Distribution comparison

In [ ]:
import torch
import torch.distributions as dist
import matplotlib.pyplot as plt

def plot_priors(mu, b, x_min=None, x_max=None, num_points=1000):
    """
    Plot the PDFs of three priors centered at mu with scale b:
      • Gaussian(μ, b)
      • Laplace(μ, b)
      • Uniform(–b, b)
    
    Parameters
    ----------
    mu : float
        Location parameter for Gaussian and Laplace.
    b : float
        Scale parameter for Gaussian and Laplace; half‐width for Uniform.
    x_min, x_max : float, optional
        Min/max of x‐axis. If None, they default to μ±5b.
    num_points : int
        Number of points to plot on the x‐axis.
    """
    # 1) Define the two torch distributions
    gaussian = dist.Normal(mu, b)
    laplace  = dist.Laplace(mu, b)

    # 2) Create x‐axis
    if x_min is None or x_max is None:
        x_min = mu - 5*b
        x_max = mu + 5*b
    x = torch.linspace(x_min, x_max, num_points)

    # 3) Compute PDFs
    p_gauss   = torch.exp(gaussian.log_prob(x))
    p_laplace = torch.exp(laplace.log_prob(x))
    # Manual Uniform PDF: 1/(2b) on [–b, b], else 0
    p_uniform = torch.where(
        (x >= mu - b) & (x <= mu + b),
        torch.tensor(1.0 / (2 * b)),
        torch.tensor(0.0)
    )

    # 4) Plot
    plt.figure(figsize=(8, 5))
    plt.plot(x.numpy(), p_gauss.numpy(),   label='Gaussian(μ, b)', color='blue')
    plt.plot(x.numpy(), p_laplace.numpy(), label='Laplace(μ, b)', color='orange')
    plt.plot(x.numpy(), p_uniform.numpy(), label='Uniform(μ±b)', color='green')
    plt.title(f'Prior PDFs (μ={mu}, b={b})')
    plt.xlabel('x')
    plt.ylabel('Density')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

In [ ]:
#plot_priors(mu=0, b=10.0)

In [ ]:
#plot_priors(mu=0, b=1.0)

In [ ]:
#plot_priors(mu=0, b=0.10000000149011612)

## Train Accuracy Analysis

In [ ]:
# loop through timestamps and load the model config
best_acc_df = pd.DataFrame(columns=['timestamp', 'activation', 'prior', 'best_acc', 'prior_mu', 'prior_b'])
for ts in timestamps:
    model_config = load_model_config(ts)

    # use pandas method of concat
    best_acc_df = pd.concat([best_acc_df, pd.DataFrame({
        'timestamp': [ts],
        'activation': [model_config['activation']],
        'prior': [model_config['prior']],
        'best_acc': [model_config['best_accuracy']],
        'prior_mu': [model_config['prior_params']['mu']],
        'prior_b': [model_config['prior_params']['b']]
    })], ignore_index=True)

In [ ]:
best_acc_df

In [ ]:
best_acc_df.at[2, 'prior_b']

In [ ]:
# for each prior_b, plot all combination of activation and prior in a histogram
# invert the plot so that the x-axis is the best_acc and the y-axis is the activation and prior
# use the blue color scheme

def plot_prior_b_histogram(df, prior_b_value):
    import matplotlib.pyplot as plt
    import seaborn as sns

    # Filter the DataFrame for the specific prior_b value
    filtered_df = df[df['prior_b'] == prior_b_value]

    # Create a pivot table for plotting
    pivot_df = filtered_df.pivot_table(index='activation', columns='prior', values='best_acc', aggfunc='mean')

    # Plotting
    plt.figure(figsize=(10, 6))
    sns.heatmap(pivot_df, annot=True, cmap='Blues', cbar_kws={'label': 'Best Accuracy'})
    plt.title(f'Best Train Accuracy for Prior b = {prior_b_value}')
    plt.xlabel('Prior')
    plt.ylabel('Activation')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

In [ ]:
plot_prior_b_histogram(best_acc_df, 0.10000000149011612)

In [ ]:
plot_prior_b_histogram(best_acc_df, 1.0)

In [ ]:
plot_prior_b_histogram(best_acc_df, 10.0)

In [ ]:
best_acc_df[best_acc_df['prior_b'] == 0.10000000149011612].sort_values(by='best_acc', ascending=False)

From the results above, we can conclude that:
- uniform seemingly performs better in training across all b value (might be counterintuitive compared to what we believe in)

## Test Accuracy Analysis

In [ ]:
# grab the csv files from the shipsnet_newslate_seu_result directory for 
prediction_files = {}

for timestamp in timestamps:
    prediction_files[timestamp] = [f for f in all_files if timestamp in f and f.endswith('.csv') and f.startswith('predictions')][0]

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
best_test_acc_df = pd.DataFrame(columns=['timestamp', 'activation', 'prior', 'best_test_acc', 'prior_mu', 'prior_b'])

for ts in timestamps:
    model_config = load_model_config(ts)

    # Load the predictions
    pred_path = os.path.join('results_shipsnet_new_uniform',model_to_check, prediction_files[ts])
    predictions = pd.read_csv(pred_path)

    # Calculate the accuracy
    y_true = predictions['True Label']
    y_pred = predictions['Predicted Label']
    best_test_acc = accuracy_score(y_true, y_pred)

    # Append to the DataFrame
    best_test_acc_df = pd.concat([best_test_acc_df, pd.DataFrame({
        'timestamp': [ts],
        'activation': [model_config['activation']],
        'prior': [model_config['prior']],
        'best_test_acc': [best_test_acc],
        'prior_mu': [model_config['prior_params']['mu']],
        'prior_b': [model_config['prior_params']['b']]
    })], ignore_index=True)

In [ ]:
best_test_acc_df

In [ ]:
best_test_acc_df[best_test_acc_df['prior_b'] == 0.10000000149011612].sort_values(by='best_test_acc', ascending=False)

In [ ]:
#join the two dataframes on timestamp, activation, prior, prior_mu, and prior_b
merged_df = pd.merge(best_acc_df, best_test_acc_df, on=['timestamp', 'activation', 'prior', 'prior_mu', 'prior_b'], suffixes=('_train', '_test'))
merged_df["best_acc_diff"] = merged_df["best_acc"] - merged_df["best_test_acc"]
merged_df

In [ ]:
def plot_prior_b_histogram_test(df, prior_b_value):
    import matplotlib.pyplot as plt
    import seaborn as sns

    # Filter the DataFrame for the specific prior_b value
    filtered_df = df[df['prior_b'] == prior_b_value]

    # Create a pivot table for plotting
    pivot_df = filtered_df.pivot_table(index='activation', columns='prior', values='best_test_acc', aggfunc='mean')

    # Plotting
    plt.figure(figsize=(10, 6))
    sns.heatmap(pivot_df, annot=True, cmap='Blues', cbar_kws={'label': 'Best Accuracy'})
    plt.title(f'Test Accuracy for Prior b = {prior_b_value}')
    plt.xlabel('Prior')
    plt.ylabel('Activation')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

In [ ]:
plot_prior_b_histogram_test(merged_df, 10.0)

In [ ]:
plot_prior_b_histogram_test(merged_df, 1.0)

In [ ]:
plot_prior_b_histogram_test(merged_df, 0.10000000149011612)

From the plots above, we can conclude that:
- uniform consistently better in test accuracy

## Train - Test Accuracy Difference Analysis

In [ ]:
# same as above, but plot for the difference between best_acc and best_test_acc
# give a color scale of red if it went to minus, blue if it went to plus
import matplotlib.pyplot as plt
import seaborn as sns


def plot_prior_b_histogram_diff(df, prior_b_value):
    # Filter the DataFrame for the specific prior_b value
    filtered_df = df[df['prior_b'] == prior_b_value]

    # Create a pivot table for plotting
    pivot_df = filtered_df.pivot_table(index='activation', columns='prior', values='best_acc_diff', aggfunc='mean')

    # Plotting
    plt.figure(figsize=(10, 6))
    sns.heatmap(pivot_df, annot=True, cmap='coolwarm', center=0, cbar_kws={'label': 'Best Accuracy Difference'})
    plt.title(f'Best Accuracy Difference for Prior b = {prior_b_value}\nTrain - Test')
    plt.xlabel('Prior')
    plt.ylabel('Activation')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

In [ ]:
plot_prior_b_histogram_diff(merged_df, 10.0)

In [ ]:
plot_prior_b_histogram_diff(merged_df, 1.0)

In [ ]:
plot_prior_b_histogram_diff(merged_df, 0.10000000149011612)

In [ ]:
# for uniform 0.1, get the confusion matrix

from sklearn.metrics import confusion_matrix
def plot_confusion_matrix(y_true, y_pred, title='Confusion Matrix'):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
    plt.title(title)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

In [ ]:
merged_df

In [ ]:
merged_df.groupby(['prior_b', 'activation', 'prior']).agg({
    #'best_acc': 'mean',
    'best_acc': 'count',
    'best_test_acc': 'mean',
    'best_acc_diff': 'mean'
}).reset_index().sort_values(by='best_acc', ascending=False)

In [ ]:
#predictions = pd.read_csv(os.path.join('results_GP_shipsnet_newslate', prediction_files[timestamps[2]]))

#get the predictions object by filtering the timestamp from merged_df based on prior_b and activation
def show_cf_matrix(prior_b, prior, activation):

    target_timestmap = merged_df[
        (merged_df['prior_b'] == prior_b) & 
        (merged_df['prior'] == prior) &
        (merged_df['activation'] == activation)
    ].iloc[0, 0]

    predictions = pd.read_csv(os.path.join('results_shipsnet_new_uniform',model_to_check, prediction_files[target_timestmap]))

    plot_confusion_matrix(y_true=predictions['True Label'], 
                        y_pred=predictions['Predicted Label'], 
                        title=f'Confusion Matrix for {activation} {prior} {prior_b:.2f} Prior')

In [ ]:
show_cf_matrix(0.10000000149011612, 'uniform', 'relu6')

In [ ]:
show_cf_matrix(0.10000000149011612, 'uniform', 'relu')

In [ ]:
show_cf_matrix(10.0, 'uniform', 'actRWG')

In [ ]:
# best test accuracy
show_cf_matrix(10.0, 'uniform', 'relu')

# Weight and Bias Parameter Distribution

In [ ]:
param_files

In [ ]:
import pyro
import torch

In [ ]:
timestamp_target = '_20250806_013752'

merged_df[merged_df['timestamp'] == timestamp_target]

#store the value of the prior, prior_mu, and prior_b
target_prior = merged_df[merged_df['timestamp'] == timestamp_target]['prior'].values[0]
target_prior_mu = merged_df[merged_df['timestamp'] == timestamp_target]['prior_mu'].values[0]
target_prior_b = merged_df[merged_df['timestamp'] == timestamp_target]['prior_b'].values[0]
target_activation = merged_df[merged_df['timestamp'] == timestamp_target]['activation'].values[0]

pyro.clear_param_store()
pyro.get_param_store().set_state(torch.load(os.path.join('results_shipsnet_new_uniform','results_shipsnet_v02_01',param_files[timestamp_target]), weights_only=False))

pyro_parameter_values = {}

for name, value in pyro.get_param_store().items():
    pyro_parameter_values[name.replace("AutoUniform.","")] = value.cpu().detach().numpy()

In [ ]:
pyro_parameter_values

## Drawing Samples from the Guide

In [ ]:
model_config

In [ ]:
# import autonormal guide
from pyro.infer.autoguide import AutoNormal

In [ ]:
import torch

In [ ]:
from pyro.nn.module import PyroModule, PyroParam
from pyro.infer.autoguide import AutoGuide
from pyro.infer.autoguide.initialization import InitMessenger, init_to_feasible
from pyro.distributions import constraints
from contextlib import ExitStack

from pyro.distributions.util       import sum_rightmost
from pyro.ops.tensor_utils         import periodic_repeat
from pyro.distributions.transforms import biject_to
from pyro.infer.autoguide.utils    import (
    deep_setattr,
    deep_getattr,
    helpful_support_errors,
)

import pyro.poutine as poutine


class AutoLaplace(AutoGuide):
    """
    An AutoGuide that uses a Laplace(loc, scale) marginal for each latent.
    """
    scale_constraint = constraints.softplus_positive

    def __init__(
        self, model, *, init_loc_fn=init_to_feasible, init_scale=0.1, create_plates=None
    ):
        self.init_loc_fn = init_loc_fn
        if not isinstance(init_scale, float) or not (init_scale > 0):
            raise ValueError(f"Expected init_scale > 0, got {init_scale}")
        self._init_scale = init_scale

        model = InitMessenger(self.init_loc_fn)(model)
        super().__init__(model, create_plates=create_plates)

    def _setup_prototype(self, *args, **kwargs):
        super()._setup_prototype(*args, **kwargs)

        self._event_dims = {}
        self.locs = PyroModule()
        self.scales = PyroModule()

        for name, site in self.prototype_trace.iter_stochastic_nodes():
            # ← use helpful_support_errors directly
            with helpful_support_errors(site):
                init_loc = (
                    biject_to(site["fn"].support)
                    .inv(site["value"].detach())
                    .detach()
                )
            event_dim = site["fn"].event_dim + init_loc.dim() - site["value"].dim()
            self._event_dims[name] = event_dim

            # handle subsampling plates
            for frame in site["cond_indep_stack"]:
                full_size = frame.full_size or frame.size
                if full_size != frame.size:
                    dim = frame.dim - event_dim
                    init_loc = periodic_repeat(init_loc, full_size, dim).contiguous()

            init_scale = torch.full_like(init_loc, self._init_scale)

            deep_setattr(
                self.locs, name, PyroParam(init_loc, constraints.real, event_dim)
            )
            deep_setattr(
                self.scales,
                name,
                PyroParam(init_scale, self.scale_constraint, event_dim),
            )

    def _get_loc_and_scale(self, name):
        site_loc = deep_getattr(self.locs, name)
        site_scale = deep_getattr(self.scales, name)
        return site_loc, site_scale

    def forward(self, *args, **kwargs):
        if self.prototype_trace is None:
            self._setup_prototype(*args, **kwargs)

        plates = self._create_plates(*args, **kwargs)
        result = {}

        for name, site in self.prototype_trace.iter_stochastic_nodes():
            transform = biject_to(site["fn"].support)

            with ExitStack() as stack:
                for frame in site["cond_indep_stack"]:
                    if frame.vectorized:
                        stack.enter_context(plates[frame.name])

                site_loc, site_scale = self._get_loc_and_scale(name)

                unconstrained = pyro.sample(
                    f"{name}_unconstrained",
                    dist.Laplace(site_loc, site_scale)
                        .to_event(self._event_dims[name]),
                    infer={"is_auxiliary": True},
                )

                value = transform(unconstrained)
                if poutine.get_mask() is False:
                    log_density = 0.0
                else:
                    log_density = transform.inv.log_abs_det_jacobian(
                        value, unconstrained
                    )
                    log_density = sum_rightmost(
                        log_density,
                        log_density.dim() - value.dim() + site["fn"].event_dim,
                    )
                delta = dist.Delta(
                    value,
                    log_density=log_density,
                    event_dim=site["fn"].event_dim,
                )
                result[name] = pyro.sample(name, delta)

        return result

    @torch.no_grad()
    def median(self, *args, **kwargs):
        medians = {}
        for name, site in self.prototype_trace.iter_stochastic_nodes():
            site_loc, _ = self._get_loc_and_scale(name)
            med = biject_to(site["fn"].support)(site_loc)
            medians[name] = med.clone() if med is site_loc else med
        return medians

    @torch.no_grad()
    def quantiles(self, quantiles, *args, **kwargs):
        results = {}
        for name, site in self.prototype_trace.iter_stochastic_nodes():
            site_loc, site_scale = self._get_loc_and_scale(name)
            qs = torch.tensor(quantiles, dtype=site_loc.dtype, device=site_loc.device)
            qs = qs.reshape((-1,) + (1,) * site_loc.dim())
            qvals = dist.Laplace(site_loc, site_scale).icdf(qs)
            results[name] = biject_to(site["fn"].support)(qvals)
        return results


class AutoUniform(AutoGuide):
    """
    An AutoGuide that uses a Uniform(low, low+width) marginal for each latent.
    """
    # `width` must be positive
    width_constraint = constraints.softplus_positive

    def __init__(
        self, model, *, init_loc_fn=init_to_feasible, init_scale=0.1, create_plates=None
    ):
        self.init_loc_fn = init_loc_fn
        if not isinstance(init_scale, float) or not (init_scale > 0):
            raise ValueError(f"Expected init_scale > 0, got {init_scale}")
        self._init_scale = init_scale

        model = InitMessenger(self.init_loc_fn)(model)
        super().__init__(model, create_plates=create_plates)

    def _setup_prototype(self, *args, **kwargs):
        super()._setup_prototype(*args, **kwargs)
        self._event_dims = {}
        self.lows = PyroModule()
        self.widths = PyroModule()

        for name, site in self.prototype_trace.iter_stochastic_nodes():
            # 1. get an unconstrained init_loc (inverse‐transform of site["value"])
            with helpful_support_errors(site):
                init_loc = (
                    biject_to(site["fn"].support)
                    .inv(site["value"].detach())
                    .detach()
                )
            event_dim = site["fn"].event_dim + init_loc.dim() - site["value"].dim()
            self._event_dims[name] = event_dim

            # 2. if subsampled, expand back to full size
            for frame in site["cond_indep_stack"]:
                full_size = frame.full_size or frame.size
                if full_size != frame.size:
                    dim = frame.dim - event_dim
                    init_loc = periodic_repeat(init_loc, full_size, dim).contiguous()

            # 3. build initial low & width around that init_loc
            init_low   = init_loc - self._init_scale
            init_width = torch.full_like(init_loc, 2.0 * self._init_scale)

            # 4. register as PyroParams
            deep_setattr(
                self.lows,  name,
                PyroParam(init_low,   constraints.real,             event_dim),
            )
            deep_setattr(
                self.widths, name,
                PyroParam(init_width, self.width_constraint,       event_dim),
            )

    def _get_low_and_width(self, name):
        low   = deep_getattr(self.lows,  name)
        width = deep_getattr(self.widths, name)
        return low, width

    def forward(self, *args, **kwargs):
        if self.prototype_trace is None:
            self._setup_prototype(*args, **kwargs)

        plates = self._create_plates(*args, **kwargs)
        result = {}

        for name, site in self.prototype_trace.iter_stochastic_nodes():
            transform = biject_to(site["fn"].support)
            with ExitStack() as stack:
                for frame in site["cond_indep_stack"]:
                    if frame.vectorized:
                        stack.enter_context(plates[frame.name])

                low, width = self._get_low_and_width(name)
                # draw unconstrained latent from Uniform(low, low + width)
                unconstrained = pyro.sample(
                    f"{name}_unconstrained",
                    dist.Uniform(low, low + width).to_event(self._event_dims[name]),
                    infer={"is_auxiliary": True},
                )

                # map into constrained space
                value = transform(unconstrained)
                if poutine.get_mask() is False:
                    log_density = 0.0
                else:
                    log_density = transform.inv.log_abs_det_jacobian(
                        value, unconstrained
                    )
                    log_density = sum_rightmost(
                        log_density,
                        log_density.dim() - value.dim() + site["fn"].event_dim,
                    )
                delta = dist.Delta(
                    value,
                    log_density=log_density,
                    event_dim=site["fn"].event_dim,
                )
                result[name] = pyro.sample(name, delta)

        return result

    @torch.no_grad()
    def median(self, *args, **kwargs):
        """
        Posterior median is just the 0.5‐quantile of Uniform = low + 0.5*width
        """
        medians = {}
        for name, site in self.prototype_trace.iter_stochastic_nodes():
            low, width = self._get_low_and_width(name)
            med = biject_to(site["fn"].support)(low + 0.5 * width)
            medians[name] = med.clone() if med is low else med
        return medians

    @torch.no_grad()
    def quantiles(self, quantiles, *args, **kwargs):
        """
        Posterior quantiles via Uniform.icdf(q).
        """
        results = {}
        qs = torch.tensor(quantiles)
        for name, site in self.prototype_trace.iter_stochastic_nodes():
            low, width = self._get_low_and_width(name)
            # shape: [len(quantiles), *low.shape]
            qvals = dist.Uniform(low, low + width).icdf(qs.reshape((-1,) + (1,) * low.dim()))
            results[name] = biject_to(site["fn"].support)(qvals)
        return results

In [ ]:
from pyro.nn import PyroModule, PyroSample

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import pyro
import pyro.distributions as dist
from pyro.nn import PyroModule, PyroSample

In [ ]:
# Added
class UniformReal(dist.Uniform):
    @property
    def support(self):
        return constraints.real

class BayesShipsCNNSmartpool(PyroModule):
    def __init__(
        self,
        num_classes=2,   # now 2 for Categorical
        device=torch.device("cuda"),
        activation='relu',
        prior_dist='gaussian',
        mu=0.0,
        b=1.0,
        prior_params=None,
        smartpool_switch = False,
        pool_threshold=10.0,
        pool_detect_only=False,
        dropout_switch=False,
        dropout_p=0.5
    ):
        super().__init__()
        self.device = device

        # Activation setup
        if isinstance(activation, str):
            act_map = {
                'relu': F.relu,
                'tanh': torch.tanh,
                'sigmoid': torch.sigmoid,
                'sinusoidal': torch.sin,
                'relu6': F.relu6,
                'leaky_relu': F.leaky_relu,
                'selu': F.selu,
                'wg': self.actWG,
                'rwg': self.actRWG,
            }
            self.activation_fn = act_map[activation]
        elif callable(activation):
            self.activation_fn = activation
        else:
            raise ValueError("activation must be a string or callable")

        # Prior setup
        self.prior_dist = prior_dist
        params = {'mu': mu, 'b': b} if prior_params is None else prior_params
        self.prior_mu = torch.tensor(params['mu'], device=device, dtype=torch.float32)
        self.prior_b  = torch.tensor(params['b'], device=device, dtype=torch.float32)

        print(f"[INFO] Using prior: {self.prior_dist} (mu={self.prior_mu.item()}, b={self.prior_b.item()})")

        # Layers
        self.conv1 = PyroModule[nn.Conv2d](3, 32, kernel_size=3, padding=1)
        self.conv1.weight = PyroSample(self._make_prior([32, 3, 3, 3]))
        self.conv1.bias   = PyroSample(self._make_prior([32]))

        self.conv2 = PyroModule[nn.Conv2d](32, 64, kernel_size=3, padding=1)
        self.conv2.weight = PyroSample(self._make_prior([64, 32, 3, 3]))
        self.conv2.bias   = PyroSample(self._make_prior([64]))

        if not smartpool_switch:
            self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        elif smartpool_switch:

            self.pool = SmartPool(
                kernel_size=2,
                stride=2,
                threshold=pool_threshold,
                detect_only=pool_detect_only
            )

        self.dropout_switch = dropout_switch

        if self.dropout_switch:
            self.dropout = nn.Dropout(p=dropout_p)

        self.fc1 = PyroModule[nn.Linear](64 * 16 * 16, num_classes)
        self.fc1.weight = PyroSample(self._make_prior([num_classes, 64 * 16 * 16]))
        self.fc1.bias   = PyroSample(self._make_prior([num_classes]))

    def actWG(self, x, alpha=1.0):
        return x * torch.exp(-alpha * x ** 2)

    def actRWG(self, x, alpha=1.0):
        wg = x * torch.exp(-alpha * x ** 2)
        return torch.max(torch.zeros_like(wg), wg)

    def _make_prior(self, shape):
        if self.prior_dist == 'gaussian':
            base = dist.Normal(self.prior_mu, self.prior_b)
        elif self.prior_dist == 'laplace':
            base = dist.Laplace(self.prior_mu, self.prior_b)
        elif self.prior_dist == 'uniform':
            #base = dist.Uniform(-self.prior_b, self.prior_b)
            base = UniformReal(-self.prior_b, self.prior_b)
        else:
            raise ValueError(f"Unsupported prior: {self.prior_dist}")
        return base.expand(shape).to_event(len(shape))

    def forward(self, x, y=None):
        x = self.activation_fn(self.conv1(x))
        x = self.pool(x)
        x = self.activation_fn(self.conv2(x))
        x = self.pool(x)

        #if self.dropout_switch:
        #    x = self.dropout(x)

        if self.dropout_switch and self.training: #ADDED ON AUGUST 02
            x = self.dropout(x)

        x = x.view(x.size(0), -1)
        logits = self.fc1(x)  # shape [batch, 2]

        if y is not None:
            with pyro.plate("data", x.size(0)):
                pyro.sample("obs", dist.Categorical(logits=logits), obs=y)
        return logits

In [ ]:
#config_files = {}
#guide_files = {}
#model_files = {}
#param_files = {}

In [ ]:
# loop thriugh timestamps and check the model config
for ts_idx, timestamp in enumerate(timestamps):
    model_config = load_model_config(timestamp)

    # Check if the model config matches the expected structure
    if model_config['activation'] == 'relu' and model_config['prior'] == 'uniform' and model_config['prior_params']['b'] == 1.0:
        print(f"Timestamp: {timestamp}, Activation: {model_config['activation']}, Prior: {model_config['prior']}")
        print(f"Prior Params: mu={model_config['prior_params']['mu']}, b={model_config['prior_params']['b']}")
        print("Model Config:", model_config)
        print("-" * 50)
        print("ts_idx:", ts_idx)
        ts_idx_set = ts_idx

In [ ]:
# 34 relu uniform 1.0

#ts_idx = 34

model_config = load_model_config(timestamps[ts_idx_set])
#model_config = load_model_config('_20250718_232229')
#model_config = load_model_config('_20250718_232106')

model_config

In [ ]:
from pyro.infer import Predictive

import torchvision.datasets as datasets
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, random_split

from torchvision.datasets import ImageFolder
import pickle

from torch.utils.data import Subset

In [ ]:
shipsnet_mean = [0.4119, 0.4243, 0.3724]
shipsnet_std = [0.1899, 0.1569, 0.1515]

In [ ]:
def load_data(batch_size=16):
    transform = transforms.Compose([
        transforms.Resize((64, 64)),
        transforms.ToTensor(),
        transforms.Normalize(mean=shipsnet_mean, 
                             std=shipsnet_std)
    ])

    #dataset = datasets.EuroSAT(root='./data', transform=transform, download=True)
    dataset = ImageFolder(
    root="data/shipsnet/foldered",
    transform=transform
    )
    torch.manual_seed(42)

    #train_size = int(0.8 * len(dataset))
    #test_size = len(dataset) - train_size
    #train_dataset, test_dataset = random_split(dataset, [train_size, test_size])
    
    with open('datasplit/shipsnet_split_indices.pkl', 'rb') as f:
        split = pickle.load(f)
        train_dataset = Subset(dataset, split['train'])
        test_dataset = Subset(dataset, split['test'])

    # Add num_workers and pin_memory for faster data loading
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, 
                             num_workers=4, pin_memory=True, persistent_workers=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size,
                            num_workers=4, pin_memory=True, persistent_workers=True)
    return train_loader, test_loader

In [ ]:
#plot the distribution of the samples in a histogram
#print the y values in its absolute value
import matplotlib.pyplot as plt
from matplotlib.ticker import ScalarFormatter

def plot_weight_distribution(samples,
                             layer_name,
                             module_name,
                             activation,
                             prior,
                             mu,
                             b):
    plt.figure(figsize=(10, 6))
    
    # Plot the histogram
    plt.hist(samples.cpu().numpy().flatten(), bins=50, density=True, alpha=0.6, color='g')
    
    # Title and axis labels
    plt.title("Weight Distribution for {}.{}\nAct : {}\nExpected distribution: {}({},{:.2f})".format(
        layer_name, 
        module_name,
        activation,
        prior,
        mu,
        b))
    
    plt.xlabel('Weight Value')
    plt.ylabel('Density')
    plt.grid(True)
    
    # Disable scientific notation on the x-axis
    ax = plt.gca()
    formatter = ScalarFormatter(useMathText=False)
    formatter.set_scientific(False)
    formatter.set_useOffset(False)
    ax.xaxis.set_major_formatter(formatter)

    plt.tight_layout()
    plt.show()

In [ ]:
model_config

In [ ]:
#reset pyro param store
pyro.clear_param_store()
pyro.get_param_store().set_state(torch.load(os.path.join('results_shipsnet_new_uniform','results_shipsnet_v02_01',param_files[timestamps[ts_idx_set]]), weights_only=False))

In [ ]:
def generate_predictive_result(timestamp,model_config, device, loader_of_interest, num_samples):
    model_config = load_model_config(timestamp)

    prior_of_interest = model_config['prior']

    if model_config['prior'] == 'sin':
        prior_of_interest = 'sinusoidal'

    #bayesian_model  = BayesShipsCNN(num_classes=2,
    #                            device=torch.device("cuda"),
    #                            activation=model_config['activation'],
    #                            prior_dist=prior_of_interest,
    #                            mu=model_config['prior_params']['mu'],
    #                            b=model_config['prior_params']['b'],
    #                            )
    
    bayesian_model = BayesShipsCNNSmartpool(num_classes=2,
        device=torch.device("cuda"),
        activation=model_config['activation'],
        prior_dist=prior_of_interest,
        mu =model_config['prior_params']['mu'],
        b=model_config['prior_params']['b'],
        )
    
    activation_iter = model_config['activation']
    prior_iter = model_config['prior']

    if prior_iter == 'gaussian':
        guide = AutoNormal(bayesian_model, init_scale=0.05).to(device)
    elif prior_iter == 'laplace':
        guide = AutoLaplace(bayesian_model, init_scale=0.05).to(device)
    elif prior_iter == 'uniform':
        guide = AutoUniform(bayesian_model, init_scale=0.05).to(device)

    #predictive = Predictive(bayesian_model,
    #                    guide=guide,
    #                    num_samples=num_samples)
    
    #x0, y0 = next(iter(loader_of_interest))
    #x0, y0 = x0.to(device), y0.to(device)
    
    #predictive_result = predictive(x0, y0)

    predictive_w = Predictive(
    bayesian_model,
    guide=guide,
    num_samples=500,
    return_sites=["conv1.weight"]
    )

    x0, _ = next(iter(loader_of_interest))
    x0 = x0.to(device)

    weight_samples = predictive_w(x0)
    W = weight_samples["conv1.weight"]

    first_neuron = W[:, 0]   # shape [500, in_channels, kH, kW]
    flat = first_neuron.flatten(start_dim=1)

    #return predictive_result
    return flat

In [ ]:
predictive_result_target = generate_predictive_result(
    timestamps[ts_idx_set],
    #'_20250718_232229',
    #'_20250718_232106',
    model_config,
    device=torch.device("cuda"),
    loader_of_interest=next(iter(load_data(batch_size=16))),
    num_samples=500
)

In [ ]:
layer_of_interest = "conv1"
module_of_interest = "weight"

samples = predictive_result_target

samples_first = samples[:, 0:1].flatten()

In [ ]:
plot_weight_distribution(samples_first,
                        layer_of_interest,
                        module_of_interest,
                        model_config['activation'],
                        model_config['prior'],
                        pyro.get_param_store()['AutoUniform.lows.conv1.weight'][0][0][0][0].cpu().detach().numpy(),
                        pyro.get_param_store()['AutoUniform.widths.conv1.weight'][0][0][0][0].cpu().detach().numpy())

In [ ]:
plot_weight_distribution(samples,
                        layer_of_interest,
                        module_of_interest,
                        model_config['activation'],
                        model_config['prior'],
                        model_config['prior_params']['mu'],
                        model_config['prior_params']['b'])

In [ ]:
# print pyro param store values for the layer of interest
for name, value in pyro.get_param_store().items():
    if layer_of_interest in name and module_of_interest in name:
        print(f"{name}: {value.cpu().detach().numpy()[0][0][0][0]}")

In [ ]:
plot_weight_distribution(samples_first,
                        layer_of_interest,
                        module_of_interest,
                        model_config['activation'],
                        model_config['prior'],
                        pyro.get_param_store()['AutoUniform.lows.conv1.weight'][0][0][0][0].cpu().detach().numpy(),
                        pyro.get_param_store()['AutoUniform.widths.conv1.weight'][0][0][0][0].cpu().detach().numpy())

## SEU test

In [ ]:
pyro.param("AutoUniform.lows.conv1.weight").data[0][0][0][0].fill_(1e3)

In [ ]:
# print pyro param store values for the layer of interest
for name, value in pyro.get_param_store().items():
    if layer_of_interest in name and module_of_interest in name:
        print(f"{name}: {value.cpu().detach().numpy()[0][0][0][0]}")

In [ ]:
pyro.get_param_store()['AutoUniform.lows.conv1.weight'][0][0][0][0].cpu().detach().numpy()

In [ ]:
predictive_result_target_new = generate_predictive_result(
    timestamps[ts_idx_set],
    #'_20250718_232229',
    #'_20250718_232106',
    model_config,
    device=torch.device("cuda"),
    loader_of_interest=next(iter(load_data(batch_size=16))),
    num_samples=500
)

In [ ]:
layer_of_interest = "conv1"
module_of_interest = "weight"

samples_new = predictive_result_target_new

samples_new_first = samples_new[:, 0:1].flatten()

In [ ]:
plot_weight_distribution(samples_new_first,
                        layer_of_interest,
                        module_of_interest,
                        model_config['activation'],
                        model_config['prior'],
                        pyro.get_param_store()['AutoUniform.lows.conv1.weight'][0][0][0][0].cpu().detach().numpy(),
                        pyro.get_param_store()['AutoUniform.widths.conv1.weight'][0][0][0][0].cpu().detach().numpy())

In [ ]:
samples_new_first